spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        hikari:
            minimumIdle: 5
            maximumPoolSize: 20
            idleTimeout: 30000
            poolName: SpringBootJPAHikariCP
            maxLifetime: 2000000
            connectionTimeout: 30000
    jpa:
        hibernate:
            dll-auto: none
        generate-dll: true
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    liquibase:
        change-log: classpath:liquibase-changeLog.xml
        enabled: true
    mail:
        host: localhost
        port: 1025
        username:
        password:
        properties:
            mail:
                smtp:
                    auth: false
                    starttls:
                        enable: false
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
server:
    port: 8081

notification:
    verificationUrl: http://localhost:8081/clients/verification?token=
